apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: redis-ss
spec:
  serviceName: "redis"
  replicas: 3 
  selector:
    matchLabels:
      app: redis 
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis  
        ports:
        - containerPort: 6379
          name: client
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:  
  - metadata:
      name: redis-data
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 5Gi
