apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  namespace: jupyter-notebook
spec:
  type: LoadBalancer
  selector:
    app: jupyter-notebook
  ports:
  - port: 80
    targetPort: 8888
