apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: jupyter/scipy-notebook:latest
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: data
          mountPath: /home/jovyan
      volumes:
      - name: data
        emptyDir: {}
