apiVersion: v1
kind: Pod
metadata:
  name: ontap-pod
spec:
  containers:
    - name: ontap-container
      image: nginx
      volumeMounts:
        - name: ontap-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ontap-volume
      persistentVolumeClaim:
        claimName: ontap-pvc
