apiVersion: v1
kind: Pod
metadata:
  name: s3-pod
spec:
  containers:
    - name: s3-container
      image: nginx
      volumeMounts:
        - name: s3-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: s3-pvc
